run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
